---
- name: Set the correct opcache filename (Ubuntu/Debian).
  ansible.builtin.set_fact:
    php_opcache_conf_filename: "10-opcache.ini"

- name: Add dependencies for PHP versions.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python3-debian
    state: present

- name: Set data for Ondrej's repo.
  ansible.builtin.set_fact:
    ondrej_repo_uri: "https://packages.sury.org/php"
    ondrej_repo_signed_by: "https://packages.sury.org/php/apt.gpg"

- name: Add Ondrej's PHP repo.
  become: true
  ansible.builtin.deb822_repository:
    state: present
    name: "ondrej-php-{{ ansible_facts['distribution_release'] }}"
    types: [deb]
    uris: ["{{ ondrej_repo_uri }}"]
    suites: ["{{ ansible_facts['distribution_release'] }}"]
    components: [main]
    signed_by: "{{ ondrej_repo_signed_by }}"
  register: php_ondrej_debian_repo

- name: Update apt caches after repo is added.
  apt: update_cache=true
  when:
    - php_ondrej_debian_repo.changed
    - ansible_facts.os_family == "Debian"
  tags: ['skip_ansible_lint']

- name: Purge PHP version packages (besides the currently chosen php_version).
  ansible.builtin.apt:
    name: "{{ php_versions_debian | reject('search', 'php' ~ php_version) | list }}"
    state: absent
    purge: true
    force: true
  register: php_version_purge

- name: Also purge php-common package if any versions were just purged.
  ansible.builtin.apt:
    name: php-common
    state: absent
    purge: true
    force: true
  when: php_version_purge.changed | bool
